services:
  api:
    container_name: card-cost-spring-app
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      BIN_API_URL: ${BIN_API_URL}
      BIN_API_KEY: ${BIN_API_KEY}

  postgres:
    container_name: postgres-spring-boot
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgresDB:/data/postgres
    ports:
      - "5332:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgresDB: